

services:
 
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  
  identity-svc:
    build:
      context: ./IdentityService
    ports:
      - "5050:8080" 

  
  product-svc:
    build:
      context: ./ProductService
    ports:
      - "5166:8080"
    depends_on:
      - mongodb

 
  api-gateway:
    build:
      context: ./ApiGateway
    ports:
      - "8000:8080"
    depends_on:
      - identity-svc
      - product-svc